### ISSUE TITLE
Crash on No Mercy

### ISSUE THREAD

**Issue by Ghstkng** [RedFlamer/Responsive-Responders#4]
Throw a molotov at Zeals, few moments later got crashed. Here is the crashlog:

Application has crashed: C++ exception
[string "lib/units/enemies/cop/actions/full_body/copac..."]:998: attempt to index local 'action_desc' (a nil value)

SCRIPT STACK

init() @mods/Responsive Responders/copactionhurt.lua:244
new() core/lib/utils/coreclass.lua:35
action_request() lib/units/enemies/cop/copmovement.lua:1154
action_request() lib/units/enemies/cop/huskcopmovement.lua:47
clbk() lib/units/enemies/cop/copmovement.lua:2054
call() lib/utils/eventlistenerholder.lua:34
_call_listeners() lib/units/enemies/cop/copdamage.lua:4477
_on_damage_received() lib/units/enemies/cop/copdamage.lua:4423
damage_fire() lib/units/enemies/cop/copdamage.lua:2180
give_fire_damage_dot() lib/units/weapons/raycastweaponbase.lua:3559
_damage_fire_dot() lib/managers/firemanager.lua:372
update() lib/managers/firemanager.lua:31
original() lib/setups/gamesetup.lua:825
update() @mods/base/req/core/Hooks.lua:264
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

**Comment by RedFlamer** [comment]
This crash is from an outdated version of responsive responders, update the mod manually and it should be resolved.
